name: "Build and push Docker images"

on:
  push:
    branches: [ "master", "add-app-image-build-action" ]

env:
  REGISTRY: ghcr.io
jobs:
  build-app:
    needs: "laravel-tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker (app)
        id: meta-app
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=sha,format=short
            type=ref,event=branch,enable=true,priority=600
            type=ref,event=tag,enable=true,priority=600
            type=ref,event=pr,prefix=pr-,enable=true,priority=600

      - name: Build and push Docker image (app)
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BASE_PHP_IMAGE=${{ env.REGISTRY }}/${{ github.repository }}-base
            BASE_PHP_IMAGE_VERSION=latest
          push: true
          pull: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}
          target: app
          #https://docs.docker.com/build/cache/backends/gha/
          #https://docs.docker.com/build/ci/github-actions/cache/
          cache-from: type=gha
          cache-to: type=gha,mode=max
