name: "Build Base PHP Image"

on: workflow_dispatch
env:
  REGISTRY: ghcr.io
jobs:
  build-base-image:
    runs-on: ubuntu-latest
    name: Build Base PHP Image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker (app)
        id: meta-app
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}-php

      - name: Build and push Docker image (app)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.base
          push: true
          pull: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}
          #https://docs.docker.com/build/cache/backends/gha/
          #https://docs.docker.com/build/ci/github-actions/cache/
          cache-from: type=gha
          cache-to: type=gha,mode=max
